//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50401.0
// 
namespace citPOINT.eSourceApp.Data.eSource {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryParameters", Namespace="http://tempuri.org/")]
    public enum QueryParameters : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BidID = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Type = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WSCall = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectType", Namespace="http://tempuri.org/")]
    public enum ObjectType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tender = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Auction = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportInfo", Namespace="http://tempuri.org/")]
    public partial class ReportInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string downloadNameField;
        
        private byte[] binaryDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string downloadName {
            get {
                return this.downloadNameField;
            }
            set {
                if ((object.ReferenceEquals(this.downloadNameField, value) != true)) {
                    this.downloadNameField = value;
                    this.RaisePropertyChanged("downloadName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] binaryData {
            get {
                return this.binaryDataField;
            }
            set {
                if ((object.ReferenceEquals(this.binaryDataField, value) != true)) {
                    this.binaryDataField = value;
                    this.RaisePropertyChanged("binaryData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.ObjectModel.ObservableCollection<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TenderInfo", Namespace="http://tempuri.org/")]
    public partial class TenderInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bidIDField;
        
        private string nameField;
        
        private System.DateTime endTimeField;
        
        private citPOINT.eSourceApp.Data.eSource.ObjectType typeField;
        
        private bool publishedField;
        
        private bool isclosedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string bidID {
            get {
                return this.bidIDField;
            }
            set {
                if ((object.ReferenceEquals(this.bidIDField, value) != true)) {
                    this.bidIDField = value;
                    this.RaisePropertyChanged("bidID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime endTime {
            get {
                return this.endTimeField;
            }
            set {
                if ((this.endTimeField.Equals(value) != true)) {
                    this.endTimeField = value;
                    this.RaisePropertyChanged("endTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public citPOINT.eSourceApp.Data.eSource.ObjectType type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool published {
            get {
                return this.publishedField;
            }
            set {
                if ((this.publishedField.Equals(value) != true)) {
                    this.publishedField = value;
                    this.RaisePropertyChanged("published");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool isclosed {
            get {
                return this.isclosedField;
            }
            set {
                if ((this.isclosedField.Equals(value) != true)) {
                    this.isclosedField = value;
                    this.RaisePropertyChanged("isclosed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="eSource.eSourceAppSoap")]
    public interface eSourceAppSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/getServerTime", ReplyAction="*")]
        System.IAsyncResult BegingetServerTime(System.AsyncCallback callback, object asyncState);
        
        System.DateTime EndgetServerTime(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/testMEthod", ReplyAction="*")]
        System.IAsyncResult BegintestMEthod(System.AsyncCallback callback, object asyncState);
        
        citPOINT.eSourceApp.Data.eSource.QueryParameters EndtestMEthod(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Login", ReplyAction="*")]
        System.IAsyncResult BeginLogin(citPOINT.eSourceApp.Data.eSource.LoginRequest request, System.AsyncCallback callback, object asyncState);
        
        citPOINT.eSourceApp.Data.eSource.LoginResponse EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/createUser", ReplyAction="*")]
        System.IAsyncResult BegincreateUser(citPOINT.eSourceApp.Data.eSource.createUserRequest request, System.AsyncCallback callback, object asyncState);
        
        citPOINT.eSourceApp.Data.eSource.createUserResponse EndcreateUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/TestUserLogin", ReplyAction="*")]
        System.IAsyncResult BeginTestUserLogin(citPOINT.eSourceApp.Data.eSource.TestUserLoginRequest request, System.AsyncCallback callback, object asyncState);
        
        citPOINT.eSourceApp.Data.eSource.TestUserLoginResponse EndTestUserLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/CreateTender", ReplyAction="*")]
        System.IAsyncResult BeginCreateTender(citPOINT.eSourceApp.Data.eSource.CreateTenderRequest request, System.AsyncCallback callback, object asyncState);
        
        citPOINT.eSourceApp.Data.eSource.CreateTenderResponse EndCreateTender(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/getReport", ReplyAction="*")]
        System.IAsyncResult BegingetReport(citPOINT.eSourceApp.Data.eSource.getReportRequest request, System.AsyncCallback callback, object asyncState);
        
        citPOINT.eSourceApp.Data.eSource.getReportResponse EndgetReport(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/getTenders", ReplyAction="*")]
        System.IAsyncResult BegingetTenders(citPOINT.eSourceApp.Data.eSource.getTendersRequest request, System.AsyncCallback callback, object asyncState);
        
        citPOINT.eSourceApp.Data.eSource.getTendersResponse EndgetTenders(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public citPOINT.eSourceApp.Data.eSource.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(citPOINT.eSourceApp.Data.eSource.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string userID) {
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public citPOINT.eSourceApp.Data.eSource.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(citPOINT.eSourceApp.Data.eSource.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createUser", Namespace="http://tempuri.org/", Order=0)]
        public citPOINT.eSourceApp.Data.eSource.createUserRequestBody Body;
        
        public createUserRequest() {
        }
        
        public createUserRequest(citPOINT.eSourceApp.Data.eSource.createUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string firstname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string lastname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string company;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool gender;
        
        public createUserRequestBody() {
        }
        
        public createUserRequestBody(string username, string password, string email, string firstname, string lastname, string company, bool gender) {
            this.username = username;
            this.password = password;
            this.email = email;
            this.firstname = firstname;
            this.lastname = lastname;
            this.company = company;
            this.gender = gender;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public citPOINT.eSourceApp.Data.eSource.createUserResponseBody Body;
        
        public createUserResponse() {
        }
        
        public createUserResponse(citPOINT.eSourceApp.Data.eSource.createUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string createUserResult;
        
        public createUserResponseBody() {
        }
        
        public createUserResponseBody(string createUserResult) {
            this.createUserResult = createUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestUserLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestUserLogin", Namespace="http://tempuri.org/", Order=0)]
        public citPOINT.eSourceApp.Data.eSource.TestUserLoginRequestBody Body;
        
        public TestUserLoginRequest() {
        }
        
        public TestUserLoginRequest(citPOINT.eSourceApp.Data.eSource.TestUserLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestUserLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        public TestUserLoginRequestBody() {
        }
        
        public TestUserLoginRequestBody(string userID) {
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestUserLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestUserLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public citPOINT.eSourceApp.Data.eSource.TestUserLoginResponseBody Body;
        
        public TestUserLoginResponse() {
        }
        
        public TestUserLoginResponse(citPOINT.eSourceApp.Data.eSource.TestUserLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestUserLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestUserLoginResult;
        
        public TestUserLoginResponseBody() {
        }
        
        public TestUserLoginResponseBody(string TestUserLoginResult) {
            this.TestUserLoginResult = TestUserLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTenderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTender", Namespace="http://tempuri.org/", Order=0)]
        public citPOINT.eSourceApp.Data.eSource.CreateTenderRequestBody Body;
        
        public CreateTenderRequest() {
        }
        
        public CreateTenderRequest(citPOINT.eSourceApp.Data.eSource.CreateTenderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTenderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public citPOINT.eSourceApp.Data.eSource.ObjectType command;
        
        public CreateTenderRequestBody() {
        }
        
        public CreateTenderRequestBody(string userID, citPOINT.eSourceApp.Data.eSource.ObjectType command) {
            this.userID = userID;
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTenderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTenderResponse", Namespace="http://tempuri.org/", Order=0)]
        public citPOINT.eSourceApp.Data.eSource.CreateTenderResponseBody Body;
        
        public CreateTenderResponse() {
        }
        
        public CreateTenderResponse(citPOINT.eSourceApp.Data.eSource.CreateTenderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTenderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateTenderResult;
        
        public CreateTenderResponseBody() {
        }
        
        public CreateTenderResponseBody(string CreateTenderResult) {
            this.CreateTenderResult = CreateTenderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReport", Namespace="http://tempuri.org/", Order=0)]
        public citPOINT.eSourceApp.Data.eSource.getReportRequestBody Body;
        
        public getReportRequest() {
        }
        
        public getReportRequest(citPOINT.eSourceApp.Data.eSource.getReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string bidID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public citPOINT.eSourceApp.Data.eSource.ObjectType type;
        
        public getReportRequestBody() {
        }
        
        public getReportRequestBody(string userID, string bidID, citPOINT.eSourceApp.Data.eSource.ObjectType type) {
            this.userID = userID;
            this.bidID = bidID;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public citPOINT.eSourceApp.Data.eSource.getReportResponseBody Body;
        
        public getReportResponse() {
        }
        
        public getReportResponse(citPOINT.eSourceApp.Data.eSource.getReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public citPOINT.eSourceApp.Data.eSource.ReportInfo getReportResult;
        
        public getReportResponseBody() {
        }
        
        public getReportResponseBody(citPOINT.eSourceApp.Data.eSource.ReportInfo getReportResult) {
            this.getReportResult = getReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTendersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTenders", Namespace="http://tempuri.org/", Order=0)]
        public citPOINT.eSourceApp.Data.eSource.getTendersRequestBody Body;
        
        public getTendersRequest() {
        }
        
        public getTendersRequest(citPOINT.eSourceApp.Data.eSource.getTendersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTendersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public citPOINT.eSourceApp.Data.eSource.ArrayOfString bidIDs;
        
        public getTendersRequestBody() {
        }
        
        public getTendersRequestBody(string userID, citPOINT.eSourceApp.Data.eSource.ArrayOfString bidIDs) {
            this.userID = userID;
            this.bidIDs = bidIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTendersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTendersResponse", Namespace="http://tempuri.org/", Order=0)]
        public citPOINT.eSourceApp.Data.eSource.getTendersResponseBody Body;
        
        public getTendersResponse() {
        }
        
        public getTendersResponse(citPOINT.eSourceApp.Data.eSource.getTendersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTendersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<citPOINT.eSourceApp.Data.eSource.TenderInfo> getTendersResult;
        
        public getTendersResponseBody() {
        }
        
        public getTendersResponseBody(System.Collections.ObjectModel.ObservableCollection<citPOINT.eSourceApp.Data.eSource.TenderInfo> getTendersResult) {
            this.getTendersResult = getTendersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface eSourceAppSoapChannel : citPOINT.eSourceApp.Data.eSource.eSourceAppSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getServerTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getServerTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.DateTime Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class testMEthodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public testMEthodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public citPOINT.eSourceApp.Data.eSource.QueryParameters Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((citPOINT.eSourceApp.Data.eSource.QueryParameters)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class createUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public createUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestUserLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TestUserLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateTenderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateTenderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public citPOINT.eSourceApp.Data.eSource.ReportInfo Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((citPOINT.eSourceApp.Data.eSource.ReportInfo)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getTendersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getTendersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<citPOINT.eSourceApp.Data.eSource.TenderInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<citPOINT.eSourceApp.Data.eSource.TenderInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class eSourceAppSoapClient : System.ServiceModel.ClientBase<citPOINT.eSourceApp.Data.eSource.eSourceAppSoap>, citPOINT.eSourceApp.Data.eSource.eSourceAppSoap {
        
        private BeginOperationDelegate onBegingetServerTimeDelegate;
        
        private EndOperationDelegate onEndgetServerTimeDelegate;
        
        private System.Threading.SendOrPostCallback ongetServerTimeCompletedDelegate;
        
        private BeginOperationDelegate onBegintestMEthodDelegate;
        
        private EndOperationDelegate onEndtestMEthodDelegate;
        
        private System.Threading.SendOrPostCallback ontestMEthodCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBegincreateUserDelegate;
        
        private EndOperationDelegate onEndcreateUserDelegate;
        
        private System.Threading.SendOrPostCallback oncreateUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginTestUserLoginDelegate;
        
        private EndOperationDelegate onEndTestUserLoginDelegate;
        
        private System.Threading.SendOrPostCallback onTestUserLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateTenderDelegate;
        
        private EndOperationDelegate onEndCreateTenderDelegate;
        
        private System.Threading.SendOrPostCallback onCreateTenderCompletedDelegate;
        
        private BeginOperationDelegate onBegingetReportDelegate;
        
        private EndOperationDelegate onEndgetReportDelegate;
        
        private System.Threading.SendOrPostCallback ongetReportCompletedDelegate;
        
        private BeginOperationDelegate onBegingetTendersDelegate;
        
        private EndOperationDelegate onEndgetTendersDelegate;
        
        private System.Threading.SendOrPostCallback ongetTendersCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public eSourceAppSoapClient() {
        }
        
        public eSourceAppSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public eSourceAppSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public eSourceAppSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public eSourceAppSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<getServerTimeCompletedEventArgs> getServerTimeCompleted;
        
        public event System.EventHandler<testMEthodCompletedEventArgs> testMEthodCompleted;
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<createUserCompletedEventArgs> createUserCompleted;
        
        public event System.EventHandler<TestUserLoginCompletedEventArgs> TestUserLoginCompleted;
        
        public event System.EventHandler<CreateTenderCompletedEventArgs> CreateTenderCompleted;
        
        public event System.EventHandler<getReportCompletedEventArgs> getReportCompleted;
        
        public event System.EventHandler<getTendersCompletedEventArgs> getTendersCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult citPOINT.eSourceApp.Data.eSource.eSourceAppSoap.BegingetServerTime(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetServerTime(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.DateTime citPOINT.eSourceApp.Data.eSource.eSourceAppSoap.EndgetServerTime(System.IAsyncResult result) {
            return base.Channel.EndgetServerTime(result);
        }
        
        private System.IAsyncResult OnBegingetServerTime(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((citPOINT.eSourceApp.Data.eSource.eSourceAppSoap)(this)).BegingetServerTime(callback, asyncState);
        }
        
        private object[] OnEndgetServerTime(System.IAsyncResult result) {
            System.DateTime retVal = ((citPOINT.eSourceApp.Data.eSource.eSourceAppSoap)(this)).EndgetServerTime(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetServerTimeCompleted(object state) {
            if ((this.getServerTimeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getServerTimeCompleted(this, new getServerTimeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getServerTimeAsync() {
            this.getServerTimeAsync(null);
        }
        
        public void getServerTimeAsync(object userState) {
            if ((this.onBegingetServerTimeDelegate == null)) {
                this.onBegingetServerTimeDelegate = new BeginOperationDelegate(this.OnBegingetServerTime);
            }
            if ((this.onEndgetServerTimeDelegate == null)) {
                this.onEndgetServerTimeDelegate = new EndOperationDelegate(this.OnEndgetServerTime);
            }
            if ((this.ongetServerTimeCompletedDelegate == null)) {
                this.ongetServerTimeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetServerTimeCompleted);
            }
            base.InvokeAsync(this.onBegingetServerTimeDelegate, null, this.onEndgetServerTimeDelegate, this.ongetServerTimeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult citPOINT.eSourceApp.Data.eSource.eSourceAppSoap.BegintestMEthod(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegintestMEthod(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        citPOINT.eSourceApp.Data.eSource.QueryParameters citPOINT.eSourceApp.Data.eSource.eSourceAppSoap.EndtestMEthod(System.IAsyncResult result) {
            return base.Channel.EndtestMEthod(result);
        }
        
        private System.IAsyncResult OnBegintestMEthod(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((citPOINT.eSourceApp.Data.eSource.eSourceAppSoap)(this)).BegintestMEthod(callback, asyncState);
        }
        
        private object[] OnEndtestMEthod(System.IAsyncResult result) {
            citPOINT.eSourceApp.Data.eSource.QueryParameters retVal = ((citPOINT.eSourceApp.Data.eSource.eSourceAppSoap)(this)).EndtestMEthod(result);
            return new object[] {
                    retVal};
        }
        
        private void OntestMEthodCompleted(object state) {
            if ((this.testMEthodCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.testMEthodCompleted(this, new testMEthodCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void testMEthodAsync() {
            this.testMEthodAsync(null);
        }
        
        public void testMEthodAsync(object userState) {
            if ((this.onBegintestMEthodDelegate == null)) {
                this.onBegintestMEthodDelegate = new BeginOperationDelegate(this.OnBegintestMEthod);
            }
            if ((this.onEndtestMEthodDelegate == null)) {
                this.onEndtestMEthodDelegate = new EndOperationDelegate(this.OnEndtestMEthod);
            }
            if ((this.ontestMEthodCompletedDelegate == null)) {
                this.ontestMEthodCompletedDelegate = new System.Threading.SendOrPostCallback(this.OntestMEthodCompleted);
            }
            base.InvokeAsync(this.onBegintestMEthodDelegate, null, this.onEndtestMEthodDelegate, this.ontestMEthodCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult citPOINT.eSourceApp.Data.eSource.eSourceAppSoap.BeginLogin(citPOINT.eSourceApp.Data.eSource.LoginRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginLogin(string userID, System.AsyncCallback callback, object asyncState) {
            citPOINT.eSourceApp.Data.eSource.LoginRequest inValue = new citPOINT.eSourceApp.Data.eSource.LoginRequest();
            inValue.Body = new citPOINT.eSourceApp.Data.eSource.LoginRequestBody();
            inValue.Body.userID = userID;
            return ((citPOINT.eSourceApp.Data.eSource.eSourceAppSoap)(this)).BeginLogin(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        citPOINT.eSourceApp.Data.eSource.LoginResponse citPOINT.eSourceApp.Data.eSource.eSourceAppSoap.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndLogin(System.IAsyncResult result) {
            citPOINT.eSourceApp.Data.eSource.LoginResponse retVal = ((citPOINT.eSourceApp.Data.eSource.eSourceAppSoap)(this)).EndLogin(result);
            return retVal.Body.LoginResult;
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userID = ((string)(inValues[0]));
            return this.BeginLogin(userID, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            bool retVal = this.EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(string userID) {
            this.LoginAsync(userID, null);
        }
        
        public void LoginAsync(string userID, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        userID}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult citPOINT.eSourceApp.Data.eSource.eSourceAppSoap.BegincreateUser(citPOINT.eSourceApp.Data.eSource.createUserRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegincreateUser(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegincreateUser(string username, string password, string email, string firstname, string lastname, string company, bool gender, System.AsyncCallback callback, object asyncState) {
            citPOINT.eSourceApp.Data.eSource.createUserRequest inValue = new citPOINT.eSourceApp.Data.eSource.createUserRequest();
            inValue.Body = new citPOINT.eSourceApp.Data.eSource.createUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.firstname = firstname;
            inValue.Body.lastname = lastname;
            inValue.Body.company = company;
            inValue.Body.gender = gender;
            return ((citPOINT.eSourceApp.Data.eSource.eSourceAppSoap)(this)).BegincreateUser(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        citPOINT.eSourceApp.Data.eSource.createUserResponse citPOINT.eSourceApp.Data.eSource.eSourceAppSoap.EndcreateUser(System.IAsyncResult result) {
            return base.Channel.EndcreateUser(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndcreateUser(System.IAsyncResult result) {
            citPOINT.eSourceApp.Data.eSource.createUserResponse retVal = ((citPOINT.eSourceApp.Data.eSource.eSourceAppSoap)(this)).EndcreateUser(result);
            return retVal.Body.createUserResult;
        }
        
        private System.IAsyncResult OnBegincreateUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            string email = ((string)(inValues[2]));
            string firstname = ((string)(inValues[3]));
            string lastname = ((string)(inValues[4]));
            string company = ((string)(inValues[5]));
            bool gender = ((bool)(inValues[6]));
            return this.BegincreateUser(username, password, email, firstname, lastname, company, gender, callback, asyncState);
        }
        
        private object[] OnEndcreateUser(System.IAsyncResult result) {
            string retVal = this.EndcreateUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OncreateUserCompleted(object state) {
            if ((this.createUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.createUserCompleted(this, new createUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void createUserAsync(string username, string password, string email, string firstname, string lastname, string company, bool gender) {
            this.createUserAsync(username, password, email, firstname, lastname, company, gender, null);
        }
        
        public void createUserAsync(string username, string password, string email, string firstname, string lastname, string company, bool gender, object userState) {
            if ((this.onBegincreateUserDelegate == null)) {
                this.onBegincreateUserDelegate = new BeginOperationDelegate(this.OnBegincreateUser);
            }
            if ((this.onEndcreateUserDelegate == null)) {
                this.onEndcreateUserDelegate = new EndOperationDelegate(this.OnEndcreateUser);
            }
            if ((this.oncreateUserCompletedDelegate == null)) {
                this.oncreateUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OncreateUserCompleted);
            }
            base.InvokeAsync(this.onBegincreateUserDelegate, new object[] {
                        username,
                        password,
                        email,
                        firstname,
                        lastname,
                        company,
                        gender}, this.onEndcreateUserDelegate, this.oncreateUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult citPOINT.eSourceApp.Data.eSource.eSourceAppSoap.BeginTestUserLogin(citPOINT.eSourceApp.Data.eSource.TestUserLoginRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTestUserLogin(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginTestUserLogin(string userID, System.AsyncCallback callback, object asyncState) {
            citPOINT.eSourceApp.Data.eSource.TestUserLoginRequest inValue = new citPOINT.eSourceApp.Data.eSource.TestUserLoginRequest();
            inValue.Body = new citPOINT.eSourceApp.Data.eSource.TestUserLoginRequestBody();
            inValue.Body.userID = userID;
            return ((citPOINT.eSourceApp.Data.eSource.eSourceAppSoap)(this)).BeginTestUserLogin(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        citPOINT.eSourceApp.Data.eSource.TestUserLoginResponse citPOINT.eSourceApp.Data.eSource.eSourceAppSoap.EndTestUserLogin(System.IAsyncResult result) {
            return base.Channel.EndTestUserLogin(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndTestUserLogin(System.IAsyncResult result) {
            citPOINT.eSourceApp.Data.eSource.TestUserLoginResponse retVal = ((citPOINT.eSourceApp.Data.eSource.eSourceAppSoap)(this)).EndTestUserLogin(result);
            return retVal.Body.TestUserLoginResult;
        }
        
        private System.IAsyncResult OnBeginTestUserLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userID = ((string)(inValues[0]));
            return this.BeginTestUserLogin(userID, callback, asyncState);
        }
        
        private object[] OnEndTestUserLogin(System.IAsyncResult result) {
            string retVal = this.EndTestUserLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTestUserLoginCompleted(object state) {
            if ((this.TestUserLoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TestUserLoginCompleted(this, new TestUserLoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TestUserLoginAsync(string userID) {
            this.TestUserLoginAsync(userID, null);
        }
        
        public void TestUserLoginAsync(string userID, object userState) {
            if ((this.onBeginTestUserLoginDelegate == null)) {
                this.onBeginTestUserLoginDelegate = new BeginOperationDelegate(this.OnBeginTestUserLogin);
            }
            if ((this.onEndTestUserLoginDelegate == null)) {
                this.onEndTestUserLoginDelegate = new EndOperationDelegate(this.OnEndTestUserLogin);
            }
            if ((this.onTestUserLoginCompletedDelegate == null)) {
                this.onTestUserLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTestUserLoginCompleted);
            }
            base.InvokeAsync(this.onBeginTestUserLoginDelegate, new object[] {
                        userID}, this.onEndTestUserLoginDelegate, this.onTestUserLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult citPOINT.eSourceApp.Data.eSource.eSourceAppSoap.BeginCreateTender(citPOINT.eSourceApp.Data.eSource.CreateTenderRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateTender(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginCreateTender(string userID, citPOINT.eSourceApp.Data.eSource.ObjectType command, System.AsyncCallback callback, object asyncState) {
            citPOINT.eSourceApp.Data.eSource.CreateTenderRequest inValue = new citPOINT.eSourceApp.Data.eSource.CreateTenderRequest();
            inValue.Body = new citPOINT.eSourceApp.Data.eSource.CreateTenderRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.command = command;
            return ((citPOINT.eSourceApp.Data.eSource.eSourceAppSoap)(this)).BeginCreateTender(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        citPOINT.eSourceApp.Data.eSource.CreateTenderResponse citPOINT.eSourceApp.Data.eSource.eSourceAppSoap.EndCreateTender(System.IAsyncResult result) {
            return base.Channel.EndCreateTender(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndCreateTender(System.IAsyncResult result) {
            citPOINT.eSourceApp.Data.eSource.CreateTenderResponse retVal = ((citPOINT.eSourceApp.Data.eSource.eSourceAppSoap)(this)).EndCreateTender(result);
            return retVal.Body.CreateTenderResult;
        }
        
        private System.IAsyncResult OnBeginCreateTender(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userID = ((string)(inValues[0]));
            citPOINT.eSourceApp.Data.eSource.ObjectType command = ((citPOINT.eSourceApp.Data.eSource.ObjectType)(inValues[1]));
            return this.BeginCreateTender(userID, command, callback, asyncState);
        }
        
        private object[] OnEndCreateTender(System.IAsyncResult result) {
            string retVal = this.EndCreateTender(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateTenderCompleted(object state) {
            if ((this.CreateTenderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateTenderCompleted(this, new CreateTenderCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateTenderAsync(string userID, citPOINT.eSourceApp.Data.eSource.ObjectType command) {
            this.CreateTenderAsync(userID, command, null);
        }
        
        public void CreateTenderAsync(string userID, citPOINT.eSourceApp.Data.eSource.ObjectType command, object userState) {
            if ((this.onBeginCreateTenderDelegate == null)) {
                this.onBeginCreateTenderDelegate = new BeginOperationDelegate(this.OnBeginCreateTender);
            }
            if ((this.onEndCreateTenderDelegate == null)) {
                this.onEndCreateTenderDelegate = new EndOperationDelegate(this.OnEndCreateTender);
            }
            if ((this.onCreateTenderCompletedDelegate == null)) {
                this.onCreateTenderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateTenderCompleted);
            }
            base.InvokeAsync(this.onBeginCreateTenderDelegate, new object[] {
                        userID,
                        command}, this.onEndCreateTenderDelegate, this.onCreateTenderCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult citPOINT.eSourceApp.Data.eSource.eSourceAppSoap.BegingetReport(citPOINT.eSourceApp.Data.eSource.getReportRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetReport(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetReport(string userID, string bidID, citPOINT.eSourceApp.Data.eSource.ObjectType type, System.AsyncCallback callback, object asyncState) {
            citPOINT.eSourceApp.Data.eSource.getReportRequest inValue = new citPOINT.eSourceApp.Data.eSource.getReportRequest();
            inValue.Body = new citPOINT.eSourceApp.Data.eSource.getReportRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.bidID = bidID;
            inValue.Body.type = type;
            return ((citPOINT.eSourceApp.Data.eSource.eSourceAppSoap)(this)).BegingetReport(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        citPOINT.eSourceApp.Data.eSource.getReportResponse citPOINT.eSourceApp.Data.eSource.eSourceAppSoap.EndgetReport(System.IAsyncResult result) {
            return base.Channel.EndgetReport(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private citPOINT.eSourceApp.Data.eSource.ReportInfo EndgetReport(System.IAsyncResult result) {
            citPOINT.eSourceApp.Data.eSource.getReportResponse retVal = ((citPOINT.eSourceApp.Data.eSource.eSourceAppSoap)(this)).EndgetReport(result);
            return retVal.Body.getReportResult;
        }
        
        private System.IAsyncResult OnBegingetReport(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userID = ((string)(inValues[0]));
            string bidID = ((string)(inValues[1]));
            citPOINT.eSourceApp.Data.eSource.ObjectType type = ((citPOINT.eSourceApp.Data.eSource.ObjectType)(inValues[2]));
            return this.BegingetReport(userID, bidID, type, callback, asyncState);
        }
        
        private object[] OnEndgetReport(System.IAsyncResult result) {
            citPOINT.eSourceApp.Data.eSource.ReportInfo retVal = this.EndgetReport(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetReportCompleted(object state) {
            if ((this.getReportCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getReportCompleted(this, new getReportCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getReportAsync(string userID, string bidID, citPOINT.eSourceApp.Data.eSource.ObjectType type) {
            this.getReportAsync(userID, bidID, type, null);
        }
        
        public void getReportAsync(string userID, string bidID, citPOINT.eSourceApp.Data.eSource.ObjectType type, object userState) {
            if ((this.onBegingetReportDelegate == null)) {
                this.onBegingetReportDelegate = new BeginOperationDelegate(this.OnBegingetReport);
            }
            if ((this.onEndgetReportDelegate == null)) {
                this.onEndgetReportDelegate = new EndOperationDelegate(this.OnEndgetReport);
            }
            if ((this.ongetReportCompletedDelegate == null)) {
                this.ongetReportCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetReportCompleted);
            }
            base.InvokeAsync(this.onBegingetReportDelegate, new object[] {
                        userID,
                        bidID,
                        type}, this.onEndgetReportDelegate, this.ongetReportCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult citPOINT.eSourceApp.Data.eSource.eSourceAppSoap.BegingetTenders(citPOINT.eSourceApp.Data.eSource.getTendersRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetTenders(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetTenders(string userID, citPOINT.eSourceApp.Data.eSource.ArrayOfString bidIDs, System.AsyncCallback callback, object asyncState) {
            citPOINT.eSourceApp.Data.eSource.getTendersRequest inValue = new citPOINT.eSourceApp.Data.eSource.getTendersRequest();
            inValue.Body = new citPOINT.eSourceApp.Data.eSource.getTendersRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.bidIDs = bidIDs;
            return ((citPOINT.eSourceApp.Data.eSource.eSourceAppSoap)(this)).BegingetTenders(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        citPOINT.eSourceApp.Data.eSource.getTendersResponse citPOINT.eSourceApp.Data.eSource.eSourceAppSoap.EndgetTenders(System.IAsyncResult result) {
            return base.Channel.EndgetTenders(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<citPOINT.eSourceApp.Data.eSource.TenderInfo> EndgetTenders(System.IAsyncResult result) {
            citPOINT.eSourceApp.Data.eSource.getTendersResponse retVal = ((citPOINT.eSourceApp.Data.eSource.eSourceAppSoap)(this)).EndgetTenders(result);
            return retVal.Body.getTendersResult;
        }
        
        private System.IAsyncResult OnBegingetTenders(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userID = ((string)(inValues[0]));
            citPOINT.eSourceApp.Data.eSource.ArrayOfString bidIDs = ((citPOINT.eSourceApp.Data.eSource.ArrayOfString)(inValues[1]));
            return this.BegingetTenders(userID, bidIDs, callback, asyncState);
        }
        
        private object[] OnEndgetTenders(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<citPOINT.eSourceApp.Data.eSource.TenderInfo> retVal = this.EndgetTenders(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetTendersCompleted(object state) {
            if ((this.getTendersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getTendersCompleted(this, new getTendersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getTendersAsync(string userID, citPOINT.eSourceApp.Data.eSource.ArrayOfString bidIDs) {
            this.getTendersAsync(userID, bidIDs, null);
        }
        
        public void getTendersAsync(string userID, citPOINT.eSourceApp.Data.eSource.ArrayOfString bidIDs, object userState) {
            if ((this.onBegingetTendersDelegate == null)) {
                this.onBegingetTendersDelegate = new BeginOperationDelegate(this.OnBegingetTenders);
            }
            if ((this.onEndgetTendersDelegate == null)) {
                this.onEndgetTendersDelegate = new EndOperationDelegate(this.OnEndgetTenders);
            }
            if ((this.ongetTendersCompletedDelegate == null)) {
                this.ongetTendersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetTendersCompleted);
            }
            base.InvokeAsync(this.onBegingetTendersDelegate, new object[] {
                        userID,
                        bidIDs}, this.onEndgetTendersDelegate, this.ongetTendersCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override citPOINT.eSourceApp.Data.eSource.eSourceAppSoap CreateChannel() {
            return new eSourceAppSoapClientChannel(this);
        }
        
        private class eSourceAppSoapClientChannel : ChannelBase<citPOINT.eSourceApp.Data.eSource.eSourceAppSoap>, citPOINT.eSourceApp.Data.eSource.eSourceAppSoap {
            
            public eSourceAppSoapClientChannel(System.ServiceModel.ClientBase<citPOINT.eSourceApp.Data.eSource.eSourceAppSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingetServerTime(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getServerTime", _args, callback, asyncState);
                return _result;
            }
            
            public System.DateTime EndgetServerTime(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.DateTime _result = ((System.DateTime)(base.EndInvoke("getServerTime", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegintestMEthod(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("testMEthod", _args, callback, asyncState);
                return _result;
            }
            
            public citPOINT.eSourceApp.Data.eSource.QueryParameters EndtestMEthod(System.IAsyncResult result) {
                object[] _args = new object[0];
                citPOINT.eSourceApp.Data.eSource.QueryParameters _result = ((citPOINT.eSourceApp.Data.eSource.QueryParameters)(base.EndInvoke("testMEthod", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLogin(citPOINT.eSourceApp.Data.eSource.LoginRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
                return _result;
            }
            
            public citPOINT.eSourceApp.Data.eSource.LoginResponse EndLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                citPOINT.eSourceApp.Data.eSource.LoginResponse _result = ((citPOINT.eSourceApp.Data.eSource.LoginResponse)(base.EndInvoke("Login", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegincreateUser(citPOINT.eSourceApp.Data.eSource.createUserRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("createUser", _args, callback, asyncState);
                return _result;
            }
            
            public citPOINT.eSourceApp.Data.eSource.createUserResponse EndcreateUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                citPOINT.eSourceApp.Data.eSource.createUserResponse _result = ((citPOINT.eSourceApp.Data.eSource.createUserResponse)(base.EndInvoke("createUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginTestUserLogin(citPOINT.eSourceApp.Data.eSource.TestUserLoginRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("TestUserLogin", _args, callback, asyncState);
                return _result;
            }
            
            public citPOINT.eSourceApp.Data.eSource.TestUserLoginResponse EndTestUserLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                citPOINT.eSourceApp.Data.eSource.TestUserLoginResponse _result = ((citPOINT.eSourceApp.Data.eSource.TestUserLoginResponse)(base.EndInvoke("TestUserLogin", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateTender(citPOINT.eSourceApp.Data.eSource.CreateTenderRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("CreateTender", _args, callback, asyncState);
                return _result;
            }
            
            public citPOINT.eSourceApp.Data.eSource.CreateTenderResponse EndCreateTender(System.IAsyncResult result) {
                object[] _args = new object[0];
                citPOINT.eSourceApp.Data.eSource.CreateTenderResponse _result = ((citPOINT.eSourceApp.Data.eSource.CreateTenderResponse)(base.EndInvoke("CreateTender", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetReport(citPOINT.eSourceApp.Data.eSource.getReportRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getReport", _args, callback, asyncState);
                return _result;
            }
            
            public citPOINT.eSourceApp.Data.eSource.getReportResponse EndgetReport(System.IAsyncResult result) {
                object[] _args = new object[0];
                citPOINT.eSourceApp.Data.eSource.getReportResponse _result = ((citPOINT.eSourceApp.Data.eSource.getReportResponse)(base.EndInvoke("getReport", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetTenders(citPOINT.eSourceApp.Data.eSource.getTendersRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getTenders", _args, callback, asyncState);
                return _result;
            }
            
            public citPOINT.eSourceApp.Data.eSource.getTendersResponse EndgetTenders(System.IAsyncResult result) {
                object[] _args = new object[0];
                citPOINT.eSourceApp.Data.eSource.getTendersResponse _result = ((citPOINT.eSourceApp.Data.eSource.getTendersResponse)(base.EndInvoke("getTenders", _args, result)));
                return _result;
            }
        }
    }
}
